# Site settings
title: "Data Readiness Levels"
email: 
description: Site for developing consensus on the use of common sub bands for describing data readiness.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://data-readiness.org" # the base hostname & protocol for your site
twitter_username: open_ml
github_username:  data-readiness

comments: true
disqus:
  shortname: data-readiness
github:
  edit: true

permalink: "/:categories/:title.html"

analytics:
  google:
    tracking_id: 

# Build settings
markdown: kramdown
future: true #false
